---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(tidyverse)
```

```{r}
sampleSheet <- read.delim("GSE132509/meta_data.tsv")
sampleSheet
```

```{r}
seurat_data <- Read10X(data.dir = "GSE132509/GSM3872434")
seurat_obj <- CreateSeuratObject(counts = seurat_data, 
                                 min.features = 100, 
                                 project = "ETV6-RUNX1_1")
```

```{r}
dirs <- slice(sampleSheet, c(2:4,9:11)) %>% 
        pull(GSE)

samples <- slice(sampleSheet, c(2:4,9:11)) %>% 
        pull(SampleName)
seurat_list <- NULL

# Create a Seurat object for each sample
for (i in 1:length(dirs)){
        message(paste("Reading data from ", dirs[i]))
        seurat_data <- Read10X(data.dir = paste0("GSE132509/",dirs[i]))
        seurat_list[[i]] <- CreateSeuratObject(counts = seurat_data, 
                                         min.features = 100, 
                                         project = samples[i])
        
}

merged_data <- merge(x = seurat_obj,y=seurat_list)
rm(seurat_list)
rm(seurat_data)
rm(seurat_obj)
```



```{r}
merged_data[["mito.ratio"]] <- PercentageFeatureSet(merged_data, pattern="^MT")/100
merged_data@meta.data
```


```{r}
qc_data <- merged_data@meta.data %>% 
  data.frame %>% 
  left_join(sampleSheet, by = c("orig.ident"="SampleName")) %>% 
  rename(SampleName = orig.ident) %>% 
  rename(nUMI = nCount_RNA, nGene=nFeature_RNA)

View(qc_data)
```


## Number of cells per-sample

```{r}
qc_data %>% 
  ggplot(aes(x = SampleName, fill=SampleGroup)) + geom_bar() + theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))
```
## UMI counts per cell

```{r}
qc_data %>% 
  ggplot(aes( x= nUMI,fill=SampleName)) + geom_density(alpha=0.2) + scale_x_log10()
```

## Genes detected per cell

```{r}
qc_data %>% 
  ggplot(aes( x= nGene,fill=SampleName)) + geom_density(alpha=0.2)
```


## Complexity

Look at the relationship between the number of UMI and number of genes detected. Should be somewhat correlated

```{r}
ggplot(qc_data, aes(x = log10(nUMI), y= log10(nGene))) + geom_point() + geom_smooth(method="lm") + facet_wrap(~SampleName)
```

Define novelty score and add to the qc data

```{r}
qc_data <- mutate(qc_data, Novelty = log10(nGene) / log10(nUMI))

ggplot(qc_data, aes(x = log10(nUMI), y= log10(nGene),col=Novelty)) + geom_point() + facet_wrap(~SampleName)

```


## Mitochondrial counts

```{r}
qc_data %>% 
  ggplot(aes(x = mito.ratio, fill=SampleName)) + geom_density(alpha=0.2) + facet_wrap(~SampleGroup) + geom_vline(xintercept = 0.2)
```

## Considering multiple QC metrics

```{r}
qc_data %>% 
  ggplot(aes(x = nUMI, y = nGene, col=mito.ratio)) + geom_point() + facet_wrap(~SampleName) + geom_vline(xintercept = 500) + geom_hline(yintercept = 250)
```

```{r}
qc_data %>% 
  ggplot(aes(x = nUMI, y = nGene, col=Novelty)) + geom_point() + facet_wrap(~SampleName) + geom_vline(xintercept = 500) + geom_hline(yintercept = 250)
```


```{r}
qc_data %>% 
  mutate(kept_in_analysis = nUMI >= 500 & nGene >=250 & Novelty > 0.8 & mito.ratio < 0.2) %>%
  count(kept_in_analysis)
```

```{r}
qc_data %>% 
  mutate(kept_in_analysis = nUMI >= 500 & nGene >=250 & Novelty > 0.8 & mito.ratio < 0.2) %>%
  ggplot(aes(x = nUMI, y = nGene, col=kept_in_analysis)) + geom_point() + facet_wrap(~SampleName) + geom_vline(xintercept = 500) + geom_hline(yintercept = 250)
```

```{r}
### Put the new meta data we've created into the Seurat object

qc_data <- data.frame(qc_data)
rownames(qc_data) <- rownames(merged_data@meta.data)

merged_data <- AddMetaData(merged_data, qc_data)

filtered_data <- subset(x = merged_data, 
                         subset= (nUMI >= 500) & 
                           (nGene >= 250) & 
                           (Novelty > 0.80) & 
                           (mito.ratio < 0.20))
dim(filtered_data)
rm(merged_data)
```


## Count filtering

```{r}
# Extract counts
counts <- GetAssayData(object = filtered_data, slot = "counts")

# Output a logical matrix specifying for each gene on whether or not there are more than zero counts per cell
nonzero <- counts > 0

```

```{r}
# Sums all TRUE values and returns TRUE if more than 10 TRUE values per gene
keep_genes <- Matrix::rowSums(nonzero) >= 10

# Only keeping those genes expressed in more than 10 cells
filtered_counts <- counts[keep_genes, ]

filtered_data <- CreateSeuratObject(filtered_counts, meta.data = filtered_data@meta.data)
```

# Sources of Variation

```{r}
cc_genes <- read.delim("regev_lab_cell_cycle_genes.txt")[,1]
s_genes <- cc_genes[1:43]
g2m_genes <- cc_genes[44:97]
```

```{r}
filtered_data <- NormalizeData(filtered_data)
seurat_phase <- CellCycleScoring(filtered_data, 
                                 g2m.features = g2m_genes, 
                                 s.features = s_genes)

# View cell cycle scores and phases assigned to cells                                 
View(seurat_phase@meta.data)  
```




```{r}
# Identify the most variable genes
seurat_phase <- FindVariableFeatures(seurat_phase, 
                     selection.method = "vst",
                     nfeatures = 2000, 
                     verbose = FALSE)
		     
# Scale the counts
seurat_phase <- ScaleData(seurat_phase)
```

```{r}
# Perform PCA
seurat_phase <- RunPCA(seurat_phase)

# Plot the PCA colored by cell cycle phase
DimPlot(seurat_phase,
        reduction = "pca",group.by = "Phase")
```

```{r}
summary(seurat_phase$mito.ratio)
seurat_phase$mito.cat <- cut(seurat_phase$mito.ratio, breaks=c(-Inf,0.02971, 0.03951,0.05186,Inf),labels=c("Low","Medium","Medium High","High"))

DimPlot(seurat_phase,
        reduction = "pca",
        group.by= "SampleGroup")

```



```{r message=FALSE}
seurat_split <- SplitObject(seurat_phase, split.by = "SampleGroup")

for(i in 1:length(seurat_split)){
  
  seurat_split[[i]] <- SCTransform(seurat_split[[i]],vars.to.regress = c("mito.ratio","nUMI","S.Score","G2M.Score") )
}

```

```{r}
integ_features <- SelectIntegrationFeatures(object.list = seurat_split, nfeatures = 3000)
seurat_split <- PrepSCTIntegration(object.list = seurat_split, anchor.features = integ_features)
```

```{r}
integ_anchors <- FindIntegrationAnchors(object.list = seurat_split, 
                                        normalization.method = "SCT",
                                        anchor.features = integ_features)

seurat_integrated <- IntegrateData(anchorset = integ_anchors,normalization.method = "SCT")
```

